moreview/urls.py
# from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.conf.urls.static import static
from django.conf import settings

from review.views import (
    ReviewCreateView,
    # ReviewCreate
)

urlpatterns = [
    path("base", TemplateView.as_view(template_name="base.html")),
    path("", include("users.urls")),
    path("", include("movie.urls")),
    path("", include("review.urls")),
    path("", include("reports.urls")),
    # path("admin/", admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movie/urls.py
from django.urls import path


from . import views

app_name = "movie"
urlpatterns = [
    path("", views.MovieListView.as_view(), name="list"),
    path("movies", views.MovieListView.as_view(), name="manage-list"),
    path("movies/<int:pk>", views.MovieDetailView.as_view(), name="detail"),
    path("movies/create", views.MovieCreateView.as_view(), name="create"),
    path("movies/<int:pk>/edit", views.MovieEditView.as_view(), name="edit"),
    path("movies/<int:pk>/delete", views.MovieDeleteView.as_view(), name="delete"),
]

users/urls.py
from django.urls import path

from . import views

app_name = "users"
urlpatterns = [
    path("register", views.UserRegisterView.as_view(), name="register"),
    path("login", views.UserLoginView.as_view(), name="login"),
    path("logout", views.UserLogoutView.as_view(), name="logout"),
    path("users", views.UserListView.as_view(), name="list"),
    path("profile", views.UserProfileView.as_view(), name="profile"),
    path("profile/edit", views.ProfileUpdateView.as_view(), name="edit-profile"),
    path("users/create", views.AdminCreateView.as_view(), name="create"),
    path("users/delete", views.UserDeleteView.as_view(), name="delete"),
    path(
        "reset-password", views.UserResetPasswordView.as_view(), name="reset-password"
    ),
    path(
        "users/<int:pk>/status",
        views.UserStatusUpdateView.as_view(),
        name="toggle-status",
    ),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.translation import gettext as _

# Create your models here.
class User(AbstractUser):
    first_name = models.CharField(_("first name"), max_length=150)
    last_name = models.CharField(_("last name"), max_length=150)
    email = models.EmailField(_("email address"))
    date_updated = models.DateTimeField(auto_now=True)

    REQUIRED_FIELDS = ["first_name", "last_name", "email"]

users/forms.py
from django import forms
from django.contrib.auth.password_validation import password_validators_help_text_html
from django.contrib.auth.password_validation import validate_password
from django.utils.translation import gettext as _
from .models import User
from django.core.exceptions import ValidationError
from django.core.validators import EmailValidator


class RegisterForm(forms.ModelForm):
    password = forms.CharField(
        label=_("password"),
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
        max_length=128,
        validators=[validate_password],
        help_text=password_validators_help_text_html(),
    )
    confirm_password = forms.CharField(
        label=_("confirm password"),
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
        max_length=128,
    )

    class Meta:
        model = User
        fields = [
            "username",
            "first_name",
            "last_name",
            "email",
            "password",
            "confirm_password",
        ]
        error_messages = {
            "email": {
                "invalid": _("Please input a valid email"),
            },
        }

    def clean(self):
        cleaned_data = super(RegisterForm, self).clean()

        if cleaned_data.get("password") != cleaned_data.get("confirm_password"):
            self.add_error("password", _("Password does not match confirm password"))

        return cleaned_data


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = [
            "first_name",
            "last_name",
            "email",
        ]


class AdminCreateForm(forms.ModelForm):
    password = forms.CharField(
        label=_("password"),
        widget=forms.PasswordInput(),
        max_length=128,
        validators=[validate_password],
        help_text=password_validators_help_text_html(),
    )

    class Meta:
        model = User
        fields = [
            "username",
            "first_name",
            "last_name",
            "email",
            "password",
        ]
        error_messages = {
            "email": {
                "invalid": _("Please input a valid email"),
            },
        }

users/views.py
from django.contrib.auth import login, logout
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.hashers import make_password
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.views import PasswordChangeView
from django.shortcuts import redirect, render
from django.urls.base import reverse, reverse_lazy
from django.views.generic.detail import DetailView
from django.views.generic.edit import FormView, CreateView, UpdateView
from django.views.generic.list import ListView
from django.contrib import messages
from moreview import settings
from .forms import RegisterForm, ProfileUpdateForm, AdminCreateForm
from .models import User
from django.utils.translation import gettext as _


# Create your views here.
class UserRegisterView(FormView):
    template_name = "register.html"
    form_class = RegisterForm
    success_url = settings.LOGIN_REDIRECT_URL

    def form_valid(self, form):
        user = form.save(commit=False)

        user.set_password(user.password)
        user.save()

        login(self.request, user)

        return super().form_valid(form)


class UserLoginView(LoginView):
    template_name = "login.html"


class UserLogoutView(LogoutView):
    http_method_names = ["post"]

    def get_redirect_url(self):
        return ""


class UserListView(UserPassesTestMixin, ListView):
    template_name = "user_list.html"
    model = User
    login_url = reverse_lazy("users:login")

    def test_func(self):
        return self.request.user.is_superuser

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context["form"] = (
            AdminCreateForm(data=self.request.session.get("admin-create-form"))
            if self.request.session.get("admin-create-form")
            else AdminCreateForm()
        )
        context["object_list"] = User.objects.all().order_by("id")

        return context


class UserProfileView(LoginRequiredMixin, DetailView):
    template_name = "profile.html"
    model = User
    login_url = reverse_lazy("users:login")

    def get(self, request, *args, **kwargs):
        if self.kwargs.get(self.pk_url_kwarg, "") == "":
            self.kwargs.update({"pk": request.user.pk})
        elif not request.user.is_superuser:
            return redirect(reverse_lazy("users:profile"))

        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["profile_update_form"] = (
            ProfileUpdateForm(data=self.request.session.get("profile-update-form"))
            if self.request.session.get("profile-update-form")
            else ProfileUpdateForm(instance=self.object)
        )
        context["reset_password_form"] = (
            PasswordChangeForm(
                user=self.request.user,
                data=self.request.session.get("reset-password-form"),
            )
            if self.request.session.get("reset-password-form")
            else PasswordChangeForm(user=self.request.user)
        )
        return context


class ProfileUpdateView(LoginRequiredMixin, UpdateView):
    model = User
    form_class = ProfileUpdateForm
    success_url = reverse_lazy("users:profile")
    login_url = reverse_lazy("users:login")

    def get(self, request, *args, **kwargs):
        return redirect(reverse("users:profile"))

    def post(self, request, *args, **kwargs):
        self.kwargs.update({"pk": request.user.pk})
        return super().post(request, *args, **kwargs)

    def form_valid(self, form):
        self.request.session["profile-update-form"] = None
        return super().form_valid(form)

    def form_invalid(self, form):
        self.request.session["profile-update-form"] = form.data
        return redirect(reverse("users:profile"))


class AdminCreateView(UserPassesTestMixin, CreateView):
    model = User
    form_class = AdminCreateForm
    success_url = reverse_lazy("users:list")
    login_url = reverse_lazy("users:login")

    def test_func(self):
        return self.request.user.is_superuser

    def get(self, request, *args, **kwargs):
        return redirect(reverse("users:list"))

    def form_valid(self, form):
        form.instance.password = make_password(form.instance.password)
        form.instance.is_superuser = True
        self.request.session["admin-create-form"] = None
        return super().form_valid(form)

    def form_invalid(self, form):
        self.request.session["admin-create-form"] = form.data
        return redirect(f"{reverse('users:list')}#create-admin")


class UserDeleteView(LoginRequiredMixin, UpdateView):
    model = User
    fields = []
    success_url = reverse_lazy("movie:list")
    login_url = reverse_lazy("users:login")

    def get(self, request, *args, **kwargs):
        return redirect(reverse("users:profile"))

    def post(self, request, *args, **kwargs):
        self.kwargs.update({"pk": request.user.pk})
        return super().post(request, *args, **kwargs)

    def form_valid(self, form):
        form.instance.is_active = False
        logout(self.request)
        return super().form_valid(form)


class UserResetPasswordView(LoginRequiredMixin, PasswordChangeView):
    success_url = reverse_lazy("users:profile")
    login_url = reverse_lazy("users:login")

    def get(self, request, *args, **kwargs):
        return redirect(reverse("users:profile"))

    def post(self, request, *args, **kwargs):
        self.kwargs.update({"pk": request.user.pk})
        return super().post(request, *args, **kwargs)

    def form_valid(self, form):
        self.request.session["reset-password-form"] = None
        messages.success(self.request, _("Reset password successfully"))
        return super().form_valid(form)

    def form_invalid(self, form):
        self.request.session["reset-password-form"] = form.data
        return redirect(f"{reverse('users:profile')}#reset-password")


class UserStatusUpdateView(UserPassesTestMixin, UpdateView):
    model = User
    fields = []
    success_url = reverse_lazy("users:list")
    login_url = reverse_lazy("users:login")

    def test_func(self):
        return (
            self.request.user.is_superuser and self.request.user.pk != self.kwargs["pk"]
        )

    def get(self, request, *args, **kwargs):
        return redirect(reverse("users:list"))

    def form_valid(self, form):
        form.instance.is_active = not form.instance.is_active
        return super().form_valid(form)

    def form_invalid(self, form):
        return redirect(reverse("users:list"))

users/templates/login.html
{% extends 'base.html' %}

{% block content %}
    {% load i18n crispy_forms_tags %}

    <div class="align-self-center my-auto px-2 col-12 col-lg-6">
        <h1 class="mb-3 text-capitalize">{% trans "login" %} <i class="fa-solid fa-right-to-bracket"></i></h1>

        <form action="{% url 'users:login' %}" method="POST">
            {% csrf_token %}
            {{ form|crispy }}

            <div class="mt-4 d-flex justify-content-center  align-items-center gap-2">
                <button class="btn btn-custom-primary" type="submit">{% trans 'login' %}</button>
                <a type="button" class="text-muted text-capitalize"
                   href="{% url 'users:register' %}">
                    {% trans 'register' %}
                </a>
            </div>
        </form>
    </div>
{% endblock %}

users/templates/profile.html
<!-- profile -->
{% extends 'base.html' %}

{% block content %}
    {% load i18n crispy_forms_tags %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
            {{ message }}
        </div>
        {% endfor %}

    <div class="align-self-center my-auto px-2 col-12 col-lg-6">
        <h1 class="mb-3 text-capitalize">{% trans 'profile' %} <i class="fa-solid fa-circle-user"></i></h1>

        <div class="mb-3">
            <p class="text-capitalize">{% trans 'username' %}</p>
            <p>{{ request.user.username }}</p>
        </div>

        <form action="{% url 'users:edit-profile' %}" method="post">
            {% csrf_token %}
            {{ profile_update_form|crispy }}

            <div class="d-flex justify-content-center mt-4 gap-2">
                <button class="btn btn-custom-primary text-capitalize" type="submit">{% trans 'save' %}</button>
                <button id="resetPwdbtn" class="btn btn-secondary text-capitalize" type="button" data-bs-toggle="modal"
                        data-bs-target="#resetPwd">
                    {% trans 'reset password' %}
                </button>
                <button class="btn btn-danger text-capitalize" type="button" data-bs-toggle="modal"
                        data-bs-target="#disabledAcc">
                    {% trans 'disable account' %}
                </button>
            </div>
        </form>
    </div>

    <!-- Disable Account Modal -->
    <div class="modal fade" id="disabledAcc" tabindex="-1" aria-labelledby="disabledAccLabel"
         aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <p class="modal-title fs-5 text-capitalize" id="disabledAccLabel">
                        {% trans 'disable account' %}
                    </p>

                    <button type="button" class="btn-close" data-bs-dismiss="modal"
                            aria-label="Close"></button>
                </div>

                <div class="modal-body">
                    <p>{% trans 'Please confirm to disable account.' %}</p>
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
                        {% trans 'cancel' %}
                    </button>

                    <form method="post" action="{% url 'users:delete' %}">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger">{% trans 'disable' %}</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <!-- Reset Password Modal -->
    <div class="modal fade" id="resetPwd" tabindex="-1" aria-labelledby="resetPwdLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <p class="modal-title fs-5 text-capitalize" id="resetPwdLabel">{% trans 'reset password' %}</p>

                    <button type="button" class="btn-close" data-bs-dismiss="modal"
                            aria-label="Close"></button>
                </div>

                <form method="post" action="{% url 'users:reset-password' %}">
                    <div class="modal-body">
                        {% csrf_token %}
                        {{ reset_password_form|crispy }}
                    </div>

                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary text-capitalize" data-bs-dismiss="modal">
                            {% trans 'cancel' %}
                        </button>
                        <button type="submit" class="btn btn-custom-primary">{% trans 'confirm' %}</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    
{% endblock %}

{% block script %}
    <script type="application/javascript">
        var url = location.href
        if (url.includes('#reset-password')){
            document.getElementById("resetPwdbtn").click();
        } 
    </script>
{% endblock %}

users/templates/register.html
{% extends 'base.html' %}

{% block content %}
    {% load i18n crispy_forms_tags %}

    <div class="align-self-center my-auto px-2 col-12 col-lg-6">
        <h1 class="mb-3 text-capitalize">{% trans 'register' %} <i class="fa-solid fa-user-plus"></i></h1>

        <form action="{% url 'users:register' %}" method="POST">
            {% csrf_token %}
	    {{ form|crispy }}

            <div class="mt-4 d-flex justify-content-center">
                <button class="btn btn-custom-primary text-capitalize" type="submit">
                    {% trans 'register' %}
                </button>
            </div>
        </form>
    </div>
{% endblock %}

{% block script %}
<script type="application/javascript">
        var email = document.querySelector('input[type="email"]');
	email.setAttribute("maxlength", "254")
        email.oninvalid = function(e) {
		e.target.setCustomValidity("");
		if (e.target.validity.valid) {
			comsole.log('valid')
			if(e.target.value.search(/[.][.]/g) >= 0){
				e.target.setCustomValidity("請輸入有效的信箱。");
			}
                       	if(e.target.value.search(/[\u4e00-\u9fa5]/g) >= 0 || e.target.value.search("xn--") >= 0){
                               	e.target.setCustomValidity("請移除中文字。");
                       	}else if(e.target.value.search(/[\uFF01-\uFF5E]/g) >= 0){
                               	e.target.setCustomValidity("請移除全形字母。");
                        }
		}else if(e.target.validity.typeMismatch){
			if(e.target.value.search(/[\u4e00-\u9fa5]/g) >= 0 || e.target.value.search("xn--") >= 0){
                                e.target.setCustomValidity("請移除中文字。");
                        }else if(e.target.value.search(/[\uFF01-\uFF5E]/g) >= 0){
                                e.target.setCustomValidity("請移除全形字母。");
                        }
		}else if (!e.target.validity.valid) {
                        if (e.target.value.length == 0) {
                                e.target.setCustomValidity("請填寫此欄位。");
			}
                }else if (e.target.validity.tooLong){
                         e.target.setCustomValidity("超過最大長度限制，請重新輸入。")
		}else {
                         e.target.setCustomValidity("請輸入有效的信箱。");
                }
        };
</script>
{% endblock %}

users/templates/user_list.html
<!--list user accounts -->
{% extends 'base.html' %}

{% block content %}
    {% load i18n crispy_forms_tags %}

    <div class="container px-2">
        <h1 class="text-center text-capitalize mb-4">{% trans 'user list' %}</h1>

        <div class="mb-2 d-flex justify-content-between">
            <p class="fs-2 mb-0 text-capitalize">{% trans 'admin' %}</p>

            <button id="createAdmin" class="btn btn-custom-primary text-capitalize" data-bs-toggle="collapse"
                    data-bs-target="#create_admin_form"
                    aria-expanded="false" aria-controls="create_admin_form">
                <i class="fa-solid fa-user-plus"></i> {% trans 'create admin' %}
            </button>
        </div>

        <div class="collapse mb-2" id="create_admin_form">
            <form action="{% url 'users:create' %}" method="POST">
                {% csrf_token %}
                {{ form|crispy }}

                <div class="d-flex justify-content-center">
                    <button class="btn btn-custom-primary text-capitalize" type="submit">{% trans 'create' %}</button>
                </div>
            </form>
        </div>

        <div class="table-responsive overflow-hidden">
            <table class="table table-hover align-middle mb-4">
                <thead>
                <tr>
                    <th scope="col" class="text-capitalize">{% trans 'username' %}</th>
                    <th scope="col" class="text-capitalize">{% trans 'full name' %}</th>
                    <th scope="col" class="text-capitalize">{% trans 'email address' %}</th>
                    <th scope="col" class="text-capitalize">{% trans 'status' %}</th>
                </tr>
                </thead>
                <tbody>
                {% for user in object_list %}
                    {% if user.is_superuser %}
                        <tr>
                            <td>{{ user.username }}</td>
                            <td>{{ user.get_full_name }}</td>
                            <td>{{ user.email }}</td>
                            <td>
                                <form method="post" action="{% url 'users:toggle-status' pk=user.pk %}">
                                    {% csrf_token %}
                                    <button class="btn btn-link" type="submit">
                                        {% if user.is_active %}
                                            <span class="badge rounded-pill bg-custom-primary text-capitalize">{% trans 'active' %}</span>
                                        {% else %}
                                            <span class="badge rounded-pill bg-danger text-capitalize">{% trans 'disabled' %}</span>
                                        {% endif %}
                                    </button>
                                </form>
                            </td>
                        </tr>
                    {% endif %}
                {% endfor %}
                </tbody>
            </table>
        </div>

        <p class="mb-2 fs-2" class="text-capitalize">{% trans 'user' %}</p>

        <div class="table-responsive">
            <table class="table table-hover align-middle">
                <thead>
                <tr>
                    <th scope="col" class="text-capitalize">{% trans 'username' %}</th>
                    <th scope="col" class="text-capitalize">{% trans 'full name' %}</th>
                    <th scope="col" class="text-capitalize">{% trans 'email address' %}</th>
                    <th scope="col" class="text-capitalize">{% trans 'status' %}</th>
                </tr>
                </thead>
                <tbody>
                {% for user in object_list %}
                    {% if not user.is_superuser %}
                        <tr>
                            <td>{{ user.username }}</td>
                            <td>{{ user.get_full_name }}</td>
                            <td>{{ user.email }}</td>
                            <td>
                                <form method="post" action="{% url 'users:toggle-status' pk=user.pk %}">
                                    {% csrf_token %}
                                    <button class="btn btn-link" type="submit">
                                        {% if user.is_active %}
                                            <span class="badge rounded-pill bg-custom-primary text-capitalize">{% trans 'active' %}</span>
                                        {% else %}
                                            <span class="badge rounded-pill bg-danger text-capitalize">{% trans 'disabled' %}</span>
                                        {% endif %}
                                    </button>
                                </form>
                            </td>
                        </tr>
                    {% endif %}
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

{% block script %}
<script type="application/javascript">
	var url = location.href
        if (url.includes('#create-admin')){
            document.getElementById("createAdmin").click();
        }

	var email = document.querySelector('input[type="email"]');
        email.setAttribute("maxlength", "254")
        email.oninvalid = function(e) {
                e.target.setCustomValidity("");
                if (e.target.validity.valid) {
                        comsole.log('valid')
                        if(e.target.value.search(/[.][.]/g) >= 0){
                                e.target.setCustomValidity("請輸入有效的信箱。");
                        }
                        if(e.target.value.search(/[\u4e00-\u9fa5]/g) >= 0 || e.target.value.search("xn--") >= 0){
                                e.target.setCustomValidity("請移除中文字。");
                        }else if(e.target.value.search(/[\uFF01-\uFF5E]/g) >= 0){
                                e.target.setCustomValidity("請移除全形字母。");
                        }
                }else if(e.target.validity.typeMismatch){
                        if(e.target.value.search(/[\u4e00-\u9fa5]/g) >= 0 || e.target.value.search("xn--") >= 0){
                                e.target.setCustomValidity("請移除中文字。");
                        }else if(e.target.value.search(/[\uFF01-\uFF5E]/g) >= 0){
                                e.target.setCustomValidity("請移除全形字母。");
                        }
                }else if (!e.target.validity.valid) {
                        if (e.target.value.length == 0) {
                                e.target.setCustomValidity("請填寫此欄位。");
                        }
                }else if (e.target.validity.tooLong){
                         e.target.setCustomValidity("超過最大長度限制，請重新輸入。")
                }else {
                         e.target.setCustomValidity("請輸入有效的信箱。");
                }
        };
</script>
{% endblock %}