moreview/urls.py
# from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.conf.urls.static import static
from django.conf import settings

from review.views import (
    ReviewCreateView,
    # ReviewCreate
)

urlpatterns = [
    path("base", TemplateView.as_view(template_name="base.html")),
    path("", include("users.urls")),
    path("", include("movie.urls")),
    path("", include("review.urls")),
    path("", include("reports.urls")),
    # path("admin/", admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movie/urls.py
from django.urls import path


from . import views

app_name = "movie"
urlpatterns = [
    path("", views.MovieListView.as_view(), name="list"),
    path("movies", views.MovieListView.as_view(), name="manage-list"),
    path("movies/<int:pk>", views.MovieDetailView.as_view(), name="detail"),
    path("movies/create", views.MovieCreateView.as_view(), name="create"),
    path("movies/<int:pk>/edit", views.MovieEditView.as_view(), name="edit"),
    path("movies/<int:pk>/delete", views.MovieDeleteView.as_view(), name="delete"),
]

reports/urls.py
from django.urls import path


from . import views

app_name = "reports"
urlpatterns = [
    path("reports/create", views.ReportCreatetView.as_view(), name="create"),
    path("reports/<int:pk>/delete", views.ReportDeleteView.as_view(), name="delete"),
    path("reports/<int:pk>/edit", views.ReportReviewView.as_view(), name="edit"),
    path("reports", views.ReportListView.as_view(), name="list"),
]

reports/models.py
from django.db import models
from users.models import User
from review.models import Review
from django.urls import reverse
from django.utils.translation import gettext as _

# Create your models here.
class Report(models.Model):
    UNDERPROCESS = 0
    SUCCESS = 1
    FAILED = 2
    TAKEBACK = 3
    REPORT_STATUS = [
        (UNDERPROCESS, "待處理"),
        (SUCCESS, "檢舉成功"),
        (FAILED, "檢舉失敗"),
        (TAKEBACK, "已撤回"),
    ]
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name=_("user"))
    review = models.ForeignKey(
        Review, on_delete=models.CASCADE, verbose_name=_("review")
    )
    handler = models.ForeignKey(
        User, on_delete=models.CASCADE, null=True, related_name=_("admin")
    )
    content = models.TextField(blank=False, null=False, max_length=500)
    status = models.IntegerField(default=UNDERPROCESS, choices=REPORT_STATUS)
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse("movie:detail", kwargs={"pk": self.pk})

reports/forms.py
from crispy_forms.bootstrap import AppendedText
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout
from django import forms
from django.utils.translation import gettext as _

from .models import Report
from users.models import User


class ReportModelForm(forms.ModelForm):
    content = forms.CharField(
        label=_("report cause"), widget=forms.Textarea(), max_length=500
    )

    class Meta:
        model = Report
        fields = ["content"]

reports/views.py
from django.urls import reverse
from django.shortcuts import render
from django.views import View
from django.views.generic import (
    CreateView,
    DetailView,
    ListView,
    UpdateView,
    DeleteView,
)
from django.http import HttpResponseRedirect, HttpResponse
from users.models import User
from review.models import Review
from .models import Report
from .forms import ReportModelForm

# Create your views here.
class ReportListView(ListView):
    model = Report
    report_template_name = "report_list.html"
    report_manage_template_name = "report_review_form.html"

    def get_template_names(self, *args, **kwargs):
        if self.request.user.is_superuser:
            return [self.report_manage_template_name]
        else:
            return [self.report_template_name]

    def get_context_data(self, **kwargs):
        context = super(ReportListView, self).get_context_data(**kwargs)

        if self.request.user.is_superuser:
            query = self.request.GET.get("q")
            status = self.request.GET.get("status")

            if query is not None and status != "all":
                report_obj = Report.objects.filter(
                    review__movie__name__contains=query, status=status
                ).order_by("-date_updated")
            elif query is not None:
                report_obj = Report.objects.filter(
                    review__movie__name__contains=query
                ).order_by("-date_updated")
            else:
                report_obj = Report.objects.all().order_by("-date_updated")

            context["status"] = status
            context["object_list"] = report_obj
        else:
            context["object_list"] = Report.objects.filter(
                user=self.request.user
            ).order_by("-date_updated")
        return context


class ReportCreatetView(View):
    def post(self, request, *args, **kwargs):
        print(self.request.POST["reviewID"])
        user = User.objects.get(id=self.request.user.id)
        review = Review.objects.get(id=request.POST["reviewID"])
        content = request.POST["content"]
        report = Report.objects.create(
            user=user,
            review=review,
            content=content,
        )
        return HttpResponseRedirect(
            reverse("movie:detail", kwargs={"pk": review.movie.pk})
        )


class ReportDeleteView(View):
    def post(self, request, *args, **kwargs):
        report = Report.objects.filter(id=self.kwargs["pk"])
        report.update(status=3)
        return HttpResponseRedirect(reverse("reports:list"))


class ReportReviewView(View):
    def post(self, request, *args, **kwargs):
        report = Report.objects.filter(id=self.kwargs["pk"])
        review = Review.objects.filter(id=report[0].review.id)
        if "accept_report" in request.POST.keys():
            report.update(status=1, handler=self.request.user)
            review.update(existed=True)
        elif "refuse_report" in request.POST.keys():
            report.update(status=2, handler=self.request.user)

        return HttpResponseRedirect(reverse("reports:list"))

reports/templates/report_list.html
<!--list reports (users) -->
{% extends 'base.html' %}

{% block content %}
    {% load i18n crispy_forms_tags %}
    
    <div class="container px-2">
	<h1 class="text-center text-capitalize mb-4">{% trans 'report list' %}</h1>
    </div>
    {% if request.user.is_authenticated %}
    <div class="container px-2">
	{% if object_list %}
            <table class="table table-hover align-middle mb-4">
                <thead>
                <tr>
                    <th scope="col" class="text-capitalize">{% trans 'movie name' %}</th>
                    <th scope="col" class="text-capitalize">{% trans 'reported review' %}</th>
                    <th scope="col" class="text-capitalize">{% trans 'report cause' %}</th>
		    <th scope="col" class="text-capitalize">{% trans 'report status' %}</th>
                </tr>
                </thead>
                <tbody>
    		{% for report in object_list %}
			<tr>
    				<td>{{report.review.movie}}</td>
    				<td>{{report.review.content}}</td>
    				<td>{{report.content}}</td>
    				<td>
                			{% if report.status == 1 %}
                			<span class="badge rounded-pill bg-success text-capitalize">{% trans 'success' %}</span>
					{% elif report.status == 2 %}
                			<span class="badge rounded-pill bg-danger text-capitalize">{% trans 'failed' %}</span>
					{% elif report.status == 3 %}
                                        <span class="badge rounded-pill bg-secondary text-capitalize">{% trans 'already takeback' %}</span>
					{% else %}
					<span class="badge rounded-pill bg-custom-primary text-capitalize" type="button" data-bs-toggle="modal" 
										      data-bs-target="#disabled_report_{{report.pk}}">{% trans 'takeback' %}
                			</span>
					{% endif %}
				</td>
			</tr>
			<!-- Diabled Report Modal -->
			<div class="modal fade" id="disabled_report_{{report.pk}}" tabindex="-1" aria-labelledby="disabledReportLabel" aria-hidden="true">
        			<div class="modal-dialog modal-dialog-centered">
            				<div class="modal-content">
                    				<div class="modal-header">
							<p class="modal-title fs-5 text-capitalize" id="disabledReportLabel">{% trans 'takeback report' %}</p>
                        				<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
		    				</div>
            	    				<div class="modal-body">
							<p>{% trans 'confirm to takeback report' %}</p>
            	    				</div>
            	    			<div class="modal-footer">
                    				<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">{% trans 'cancel' %}</button>
						<form method="post" action="{% url 'reports:delete' report.id %}">
							{% csrf_token %}
							<button type="submit" class="btn btn-danger">{% trans 'confirm' %}</button>
                    				</form>
            				</div>
            			</div>
        		</div>
    {% endfor %}
    </tbody>
	    </table>
	    {% else %}
	    	<p class="text-center">{% trans 'You did not have any reports.' %}</p>
	    {% endif %}
    </div>
    {% endif %}
{% endblock %}

reports/templates/report_review_form.html
{% extends 'base.html' %}

{% block content %}
{% load i18n %}
<div class="container px-2">
	<h1 class="text-center text-capitalize mb-4">{% trans 'report list' %}</h1>
    </div>
    {% if request.user.is_superuser %}
    <div class="container px-2">
	<form method="GET">
    		<section class="mb-4">
        		<div class="input-group">
            			<input type="text" name="q" class="form-control" placeholder="{% trans 'Search by name' %}">
				<div class="d-flex justify-content-end align-items-center gap-1 mx-1">
                			<select class="form-select w-auto" name="status" >
						<option value='all'>{% trans 'choose filters' %}</option>
                    				<option value='0' {% if status == '0' %} selected {% endif %}>
                        			{% trans 'underprocess' %}
                    				</option>
                    				<option value='1' {% if status == '1' %} selected {% endif %}>
                        			{% trans 'success' %}
                    				</option>
                    				<option value='2' {% if status == '2' %} selected {% endif %}>
                        			{% trans 'failed' %}
                    				</option>
                			</select>
				</div>
            			<button class="btn btn-custom-primary text-capitalize" type="submit">
                			{% trans "search" %} <i class="fa fa-search" aria-hidden="true"></i>
            			</button>
        		</div>
    		</section>
	</form>
    </div>
    <div class="container px-2">
	    {% if object_list %}
    	<div class="table-responsive">
            <table class="table table-hover align-middle">
		    <thead>
			    <tr>
				    <th>{% trans 'reported reviewer'%}</th>
				    <th>{% trans 'movie name' %}</th>
				<th>{% trans 'reported review' %}</th>
				<th>{% trans 'reporter' %}</th>
				<th>{% trans 'report cause' %}</th>
				<th>{% trans 'report status' %}</th>
				<th>{% trans 'validator' %}</th>
		    	</tr>
		    </thead>
		    <tbody>
			    {% for report in object_list %}
			    {% if report.status < 3 %}
			    <tr>
				<td>{{report.review.user}}</td>
        			<td>{{report.review.movie}}</td>
        			<td>{{report.review.content}}</td>
        			<td>{{report.user}}</td>
        			<td>{{report.content}}</td>
        			<td>
					{% if report.status == 1 %} <!-- 檢舉成功 -->
					<span class="badge rounded-pill bg-custom-primary text-capitalize">{% trans 'success' %}</span>
					{% elif report.status == 2 %} <!-- 檢舉失敗 -->
					<span class="badge rounded-pill bg-danger text-capitalize">{% trans 'failed' %}</span>
					{% else %} <!-- 待處理 -->
					<span class="badge rounded-pill bg-secondary text-capitalize">{% trans 'underprocess' %}</span>
               				{% endif %}
	</td>
        <td>{% if not report.handler %}

		<span class="badge rounded-pill bg-custom-primary text-capitalize" type="button" data-bs-toggle="modal" data-bs-target="#accept_report_{{report.id}}">接受</span>
        <span class="badge rounded-pill bg-danger text-capitalize" type="button" data-bs-toggle="modal" data-bs-target="#refuse_report_{{report.id}}">拒絕</span>

<!-- Accept Report Modal -->
        <div class="modal fade" id="accept_report_{{report.id}}" tabindex="-1" aria-labelledby="acceptReportLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
                  <div class="modal-content">
                         <div class="modal-header">
                               <p class="modal-title fs-5 text-capitalize" id="acceptReportLabel">審核檢舉</p>                               <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                         </div>
                         <div class="modal-body">
                               <p>是否確認該筆檢舉？</p>
                         </div>
                         <div class="modal-footer">
                               <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">{% trans 'cancel' %}</button>
                                <form action="{% url 'reports:edit' report.pk %}" method="POST">
                                     {% csrf_token %}
                                     <button class="btn bg-custom-primary" type="submit" name="accept_report" value="accept">{% trans 'confirm' %}</button>
                               </form>
                         </div>
                  </div>
                </div>
        </div>

	<!-- Refuse Report Modal -->
        <div class="modal fade" id="refuse_report_{{report.id}}" tabindex="-1" aria-labelledby="refuseReportLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
                  <div class="modal-content">
                         <div class="modal-header">
                               <p class="modal-title fs-5 text-capitalize" id="refuseReportLabel">審核檢舉</p>                               <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                         </div>
                         <div class="modal-body">
                               <p>是否拒絕該筆檢舉？</p>
                         </div>
                         <div class="modal-footer">
                               <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">{% trans 'cancel' %}</button>
                                <form action="{% url 'reports:edit' report.pk %}" method="POST">
                                     {% csrf_token %}
                                     <button class="btn btn-danger" type="submit" name="refuse_report" value="refuse">{% trans 'confirm' %}</button>
                               </form>
                         </div>
                  </div>
                </div>
        </div>
	{% else %}
                {{report.handler}}
        {% endif %}
        </td>
                            </tr>{% endif %}
                            {% endfor %}
        </tbody>

            </table>

	{% else %}
		<p class="text-center">{% trans 'Sorry, no reports match the condition.' %}</p>
    {% endif %}

    {% endif %}
{% endblock %}