moreview/urls.py
# from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.conf.urls.static import static
from django.conf import settings

from review.views import (
    ReviewCreateView,
    # ReviewCreate
)

urlpatterns = [
    path("base", TemplateView.as_view(template_name="base.html")),
    path("", include("users.urls")),
    path("", include("movie.urls")),
    path("", include("review.urls")),
    path("", include("reports.urls")),
    # path("admin/", admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movie/urls.py
from django.urls import path


from . import views

app_name = "movie"
urlpatterns = [
    path("", views.MovieListView.as_view(), name="list"),
    path("movies", views.MovieListView.as_view(), name="manage-list"),
    path("movies/<int:pk>", views.MovieDetailView.as_view(), name="detail"),
    path("movies/create", views.MovieCreateView.as_view(), name="create"),
    path("movies/<int:pk>/edit", views.MovieEditView.as_view(), name="edit"),
    path("movies/<int:pk>/delete", views.MovieDeleteView.as_view(), name="delete"),
]

movie/models.py
import datetime

from django.db import models
from django.urls import reverse
from django.utils.translation import gettext as _


# Create your models here.
class Tag(models.Model):
    name = models.CharField(_("name"), max_length=10)
    description = models.TextField(_("description"))
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


movie_grade = [
    ("普遍級", "普遍級"),
    ("保護級", "保護級"),
    ("輔12級", "輔12級"),
    ("輔15級", "輔15級"),
    ("限制級", "限制級"),
]


class Movie(models.Model):
    tag_id = models.ForeignKey(Tag, on_delete=models.CASCADE, verbose_name=_("tag"))
    name = models.CharField(_("name"), max_length=20)
    content = models.TextField(_("content"), max_length=500)
    official_site = models.URLField(_("official site"))
    time = models.PositiveSmallIntegerField(_("time"))
    image = models.ImageField(_("image"), upload_to="movies/")
    grade = models.TextField(_("grade"), choices=movie_grade)
    date_released = models.DateField(_("release date"), default=datetime.date.today)
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse("movie:detail", kwargs={"pk": self.pk})

    def __str__(self):
        return self.name

movie/forms.py
from crispy_forms.bootstrap import AppendedText
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout
from django import forms
from django.utils.translation import gettext as _

from movie.models import Movie


class MovieModelForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            "tag_id",
            "name",
            "content",
            "official_site",
            AppendedText("time", _("minutes")),
            "grade",
            "date_released",
            "image",
        )

    class Meta:
        model = Movie
        fields = [
            "tag_id",
            "name",
            "content",
            "official_site",
            "time",
            "grade",
            "date_released",
            "image",
        ]
        widgets = {
            "date_released": forms.TextInput(attrs={"type": "date"}),
        }

movie/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
from django.urls import reverse, reverse_lazy
from review.models import Review, Heart
from django.db.models import Count, Avg, Func, IntegerField, Case, When

from django.views.generic import (
    CreateView,
    DetailView,
    ListView,
    UpdateView,
    DeleteView,
)

from .forms import MovieModelForm
from review.forms import ReviewModelForm
from review.models import Review
from movie.models import Movie
from reports.models import Report
from reports.forms import ReportModelForm

# Create your views here.


class Round(Func):
    function = "Round"
    template = "%(function)s(%(expressions)s, 2)"


class MovieCreateView(UserPassesTestMixin, CreateView):
    model = Movie
    template_name = "movie_create_form.html"
    form_class = MovieModelForm
    login_url = reverse_lazy("users:login")

    def test_func(self):
        return self.request.user.is_superuser


class MovieDetailView(DetailView):
    model = Movie
    template_name = "movie_detail.html"

    def get_context_data(self, **kwargs):
        context = super(MovieDetailView, self).get_context_data(**kwargs)
        context["form"] = ReviewModelForm()
        context["report_create_form"] = ReportModelForm()

        # movie average rating
        context["movie"] = Movie.objects.annotate(
            average_rating=Round(
                Avg(
                    Case(
                        When(review__existed=False, then="review__rating"),
                        output_field=IntegerField(),
                    )
                )
            )
        ).get(id=self.kwargs["pk"])

        # sort, default : "latest"
        order = self.request.GET.get("order")
        # According to date_created
        order_query = "-date_created"
        if order == "oldest":
            order_query = "date_created"

        review_list = (
            Review.objects.filter(movie_id=self.object.id)
            .annotate(heart_number=Count("heart"))
            .order_by(order_query)
        )

        # According to number of heart
        # highest
        if order == "heart_highest":
            review_list = (
                Review.objects.filter(movie_id=self.object.id)
                .annotate(heart_number=Count("heart"))
                .order_by("-heart_number")
            )
        # lowest
        elif order == "heart_lowest":
            review_list = (
                Review.objects.filter(movie_id=self.object.id)
                .annotate(heart_number=Count("heart"))
                .order_by("heart_number")
            )

        # According to rating
        # highest
        if order == "rating_highest":
            review_list = (
                Review.objects.filter(movie_id=self.object.id)
                .annotate(heart_number=Count("heart"))
                .order_by("-rating")
            )
        # lowest
        elif order == "rating_lowest":
            review_list = (
                Review.objects.filter(movie_id=self.object.id)
                .annotate(heart_number=Count("heart"))
                .order_by("rating")
            )

        context["review_list"] = review_list
        context["order"] = order

        # Displays the hearts that the user has clicked
        heart_list = Heart.objects.all()
        context["heart_list"] = []
        for heart in heart_list:
            if heart.user.id == self.request.user.id:
                for review in context["review_list"]:
                    if heart.review.id == review.id:
                        context["heart_list"].append(
                            Heart.objects.get(
                                user=self.request.user.id, review=review.id
                            )
                        )

        context["self_review_list"] = []
        for review in context["review_list"]:
            if self.request.user.id == review.user.id and review.existed != True:
                if not self.request.user.is_superuser:
                    context["self_review_list"].append(review)

        report_list = Report.objects.filter(user=self.request.user.id)

        context["report_list"] = report_list
        context["self_report_list"] = []
        for report in report_list:
            for review in context["review_list"]:
                if report.review.id == review.id:
                    if not self.request.user.is_superuser:
                        context["self_report_list"].append(review)

        return context


class MovieListView(ListView):
    model = Movie
    home_template_name = "homepage.html"
    manage_template_name = "movie_list.html"
    queryset = Movie.objects.filter(image__contains="movies/").order_by(
        "-date_released"
    )

    def get_template_names(self, *args, **kwargs):
        if self.request.path == reverse("movie:list"):
            return [self.home_template_name]
        else:
            return [self.manage_template_name]

    def get_context_data(self, **kwargs):
        context = super(MovieListView, self).get_context_data(**kwargs)

        if self.request.path == reverse("movie:list"):
            # get request
            query = self.request.GET.get("q")
            order = self.request.GET.get("order")
            order_query = "-date_released"
            movie_obj = None
            if order == "Asc":
                order_query = "date_released"

            if query is not None:  # search
                movie_obj = Movie.objects.filter(
                    name__contains=query, image__contains="movies/"
                ).order_by(order_query)
            else:  # not search
                movie_obj = Movie.objects.filter(image__contains="movies/").order_by(
                    order_query
                )
            context["object_list"] = movie_obj
            context["order"] = order

            return context
        else:
            # get request
            query = self.request.GET.get("q")
            movie_obj = None
            if query is not None:  # serch
                movie_obj = Movie.objects.filter(name__contains=query).order_by(
                    "-date_created"
                )
            else:  # not search
                movie_obj = Movie.objects.all().order_by("-date_created")
            context["object_list"] = movie_obj
            return context


class MovieEditView(UserPassesTestMixin, UpdateView):
    form_class = MovieModelForm
    template_name = "movie_edit_form.html"
    queryset = Movie.objects.all()
    login_url = reverse_lazy("users:login")

    def test_func(self):
        return self.request.user.is_superuser


class MovieDeleteView(UserPassesTestMixin, DeleteView):
    model = Movie
    success_url = "/movies"
    login_url = reverse_lazy("users:login")

    def test_func(self):
        return self.request.user.is_superuser

    def get_success_url(self):
        return reverse("movie:manage-list")

movie/templates/homepage.html
{% extends 'base.html' %}

{% block content %}
    {% load i18n %}

    <div class="container px-2">
        <form method="GET">
            <section class="mb-4">
                <div class="input-group">
                    <input type="text" name="q" class="form-control" placeholder="{% trans 'Search by name' %}">
                    <button class="btn btn-custom-primary text-capitalize" type="submit">
                        {% trans "search" %} <i class="fa fa-search" aria-hidden="true"></i>
                    </button>
                </div>
            </section>

            <div class="d-flex justify-content-end align-items-center gap-1 mb-4">
                <span>{% trans 'Order by released date:' %}</span>
                <select class="form-select w-auto" name="order" onchange="this.form.submit();">
                    <option value='Desc' {% if order == 'Desc' %} selected {% endif %}>
                        {% trans 'Latest to Oldest' %}
                    </option>
                    <option value='Asc' {% if order == 'Asc' %} selected {% endif %}>
                        {% trans 'Oldest to Latest' %}
                    </option>
                </select>
            </div>
        </form>

        <div>
            {% if object_list %}
                <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3">
                    {% for movie in object_list %}
                        <div class="col mb-3">
                            <div class="card shadow-sm">
                                <img style="height: 300px; object-fit: contain;"
                                     src="/static/images{{ movie.image.url }}"
                                     loading="lazy">
                                <div class="card-body bg-secondary bg-opacity-25">
                                    <a href="{% url 'movie:detail' movie.pk %}"
                                       class="text-decoration-none card-text text-dark stretched-link fs-4 fw-bold">{{ movie.name }}</a>
                                    <p class="card-text text-capitalize">
                                        {% trans 'release date' %}: {{ movie.date_released|date:'Y/m/d' }}
                                    </p>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            {% else %}
                <p class="text-center">{% trans 'Sorry, no movies match the condition.' %}</p>
            {% endif %}
        </div>
    </div>
{% endblock %}

movie/templates/movie_create_form.html
{% extends 'base.html' %}

{% block content %}
    {% load i18n crispy_forms_tags %}

    <div class="align-self-center px-2 col-12 col-lg-8">
        <h1 class="text-capitalize">{% trans 'create movie' %}</h1>

        <form action="{% url 'movie:create' %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <div class="d-flex justify-content-center mt-4">
                <input type="submit" value='{% trans 'create' %}' class="btn btn-custom-primary text-capitalize"/>
            </div>
        </form>
    </div>
{% endblock %}

movie/templates/movie_edit_form.html
{% extends 'base.html' %}

{% block content %}
    {% load i18n crispy_forms_tags %}

    <div class="align-self-center px-2 col-12 col-lg-8">
        <h1 class="text-capitalize">{% trans 'edit movie' %}</h1>

        <form action="{% url 'movie:edit' movie.pk %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}

            <div class="d-flex justify-content-center mt-4">
                <input type="submit" value="{% trans 'confirm' %}" class="btn btn-custom-primary text-capitalize"/>
            </div>
        </form>
    </div>
{% endblock %}

movie/templates/movie_list.html
{% extends 'base.html' %}

{% block content %}
    {% load i18n %}

    <div class="container px-2">
        <div class="d-flex justify-content-between align-items-center mb-4">
            <h1 class="text-capitalize">{% trans 'movie list' %}</h1>

            <a class="btn btn-custom-primary text-capitalize" href="{% url 'movie:create' %}">
                <i class="fa fa-plus" aria-hidden="true"></i> {% trans 'create movie' %}
            </a>
        </div>

        <section class="mb-4">
            <form class="input-group" method="GET">
                <input type="text" name="q" class="form-control" placeholder="{% trans 'Search by name' %}">
                <button class="btn btn-custom-primary text-capitalize" type="submit">
                    {% trans "search" %} <i class="fa fa-search" aria-hidden="true"></i>
                </button>
            </form>
        </section>


        <div class="table-responsive">
            <table class="table table-hover align-middle">
                <thead>
                <tr>
                    <th scope="col" class="text-uppercase">{% trans 'id' %}</th>
                    <th scope="col" class="text-capitalize">{% trans 'name' %}</th>
                    <th scope="col" class="text-capitalize">{% trans 'release date' %}</th>
                    <th scope="col"></th>
                </tr>
                </thead>
                <tbody>
                {% for movie in object_list %}
                    <tr>
                        <th scope="row">{{forloop.counter}}</th>
                        <td>{{ movie.name }}</td>
                        <td>{{ movie.date_released|date:'Y/m/d' }}</td>
                        <td>
                            <div class="d-flex justify-content-end gap-2">
                                <a type="submit" href="{% url 'movie:edit' movie.pk %}"
                                   class="btn btn-secondary text-capitalize">
                                    {% trans 'edit' %}
                                </a>

                                <!-- Button trigger modal -->
                                <button type="button" class="btn btn-danger text-capitalize" data-bs-toggle="modal"
                                        data-bs-target="#modal" data-bs-name="{{ movie.name }}"
                                        data-bs-link="{% url 'movie:delete' movie.pk %}">
                                    {% trans 'delete' %}
                                </button>
                            </div>
                        </td>
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="4">{% trans "Sorry, no movies match the condition." %}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="modal" data-bs-backdrop="static"
         data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel"
         aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <p class="modal-title fs-5" id="staticBackdropLabel">
                        {% trans 'Confirm to delete' %} <span id="name"></span>?</p>

                    <button type="button" class="btn-close" data-bs-dismiss="modal"
                            aria-label="Close"></button>
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-outline-secondary text-capitalize"
                            data-bs-dismiss="modal">
                        {% trans 'cancel' %}
                    </button>

                    <form method="POST" action="">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger text-capitalize">{% trans 'delete' %}</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block script %}
    <script type="application/javascript">
        const modal = document.getElementById('modal')

        modal.addEventListener('show.bs.modal', event => {
            const button = event.relatedTarget
            const name = button.getAttribute('data-bs-name')
            const action = button.getAttribute('data-bs-link')

            const movieName = modal.querySelector('#name')
            const form = modal.querySelector('form')

            movieName.textContent = name
            form.action = action
        })
    </script>
{% endblock %}