moreview/urls.py
# from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.conf.urls.static import static
from django.conf import settings

from review.views import (
    ReviewCreateView,
    # ReviewCreate
)

urlpatterns = [
    path("base", TemplateView.as_view(template_name="base.html")),
    path("", include("users.urls")),
    path("", include("movie.urls")),
    path("", include("review.urls")),
    path("", include("reports.urls")),
    # path("admin/", admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movie/urls.py
from django.urls import path


from . import views

app_name = "movie"
urlpatterns = [
    path("", views.MovieListView.as_view(), name="list"),
    path("movies", views.MovieListView.as_view(), name="manage-list"),
    path("movies/<int:pk>", views.MovieDetailView.as_view(), name="detail"),
    path("movies/create", views.MovieCreateView.as_view(), name="create"),
    path("movies/<int:pk>/edit", views.MovieEditView.as_view(), name="edit"),
    path("movies/<int:pk>/delete", views.MovieDeleteView.as_view(), name="delete"),
]

reports/urls.py
from django.urls import path


from . import views

app_name = "reports"
urlpatterns = [
    path("reports/create", views.ReportCreatetView.as_view(), name="create"),
    path("reports/<int:pk>/delete", views.ReportDeleteView.as_view(), name="delete"),
    path("reports/<int:pk>/edit", views.ReportReviewView.as_view(), name="edit"),
    path("reports", views.ReportListView.as_view(), name="list"),
]

users/urls.py
from django.urls import path

from . import views

app_name = "users"
urlpatterns = [
    path("register", views.UserRegisterView.as_view(), name="register"),
    path("login", views.UserLoginView.as_view(), name="login"),
    path("logout", views.UserLogoutView.as_view(), name="logout"),
    path("users", views.UserListView.as_view(), name="list"),
    path("profile", views.UserProfileView.as_view(), name="profile"),
    path("profile/edit", views.ProfileUpdateView.as_view(), name="edit-profile"),
    path("users/create", views.AdminCreateView.as_view(), name="create"),
    path("users/delete", views.UserDeleteView.as_view(), name="delete"),
    path(
        "reset-password", views.UserResetPasswordView.as_view(), name="reset-password"
    ),
    path(
        "users/<int:pk>/status",
        views.UserStatusUpdateView.as_view(),
        name="toggle-status",
    ),
]

templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <title>{% block title %}MoReview{% endblock %}</title>
    {% load static %}
    <link rel="icon" href="{% static 'images/favicon.ico' %}">
    {# Bootstrap CSS #}
    <link rel="stylesheet" href="{% static 'css/app.css' %}">
    <!-- Custom theme CSS -->
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">

    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>

    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet"
          type="text/css"/>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800"
          rel="stylesheet" type="text/css"/>

    {# Bootstrap core JS #}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
            crossorigin="anonymous"></script>
    <!-- Core theme JS-->
    <script src="{% static 'js/scripts.js' %}"></script>
</head>
<body class="min-vh-100 d-flex flex-column">
{# Navbar #}
{% include 'base_navigation.html' %}

<div class="flex-fill mt-3 mt-lg-5 pt-5 d-flex flex-column">
    {% block content %}{% endblock %}
</div>

{% include 'base_footer.html' %}

{% block script %}{% endblock %}
</body>
</html>

templates/base_footer.html
<!-- Footer -->
<footer class="mt-3 border-top d-flex justify-content-center">
    <p class="mt-1 text-muted fst-italic">Copyright &copy; Moreview</p>
</footer>

templates/base_navigation.html
<!-- Navigation-->
{% load i18n %}

<nav class="navbar fixed-top navbar-expand-lg bg-custom-primary" id="mainNav">
    <div class="container">
        <div class="w-100 w-md-auto d-flex justify-content-between order-first order-lg-last">
            <button class="navbar-toggler py-2 px-3" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarResponsive"
                    aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <i class="fas fa-bars"></i>
            </button>

            {% url 'users:login' as login_url %}
            {% if not request.user.is_authenticated and login_url != request.path %}
                <a class="btn btn-outline-dark text-capitalize" href="{% url 'users:login' %}">{% trans "login" %}</a>
            {% endif %}
        </div>

        <div class="collapse navbar-collapse flex-fill" id="navbarResponsive">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link text-capitalize me-2"
                       href="{% url 'movie:list' %}">{% trans "homepage" %}</a>
                </li>
                {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link text-capitalize me-2"
                           href="{% url 'users:profile' %}">{% trans "profile" %}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-capitalize me-2" href="{% url 'reports:list' %}">{% trans "report list" %}</a>
                    </li>
                    {% if request.user.is_superuser %}
                        <li class="nav-item">
                            <a class="nav-link text-capitalize me-2"
                               href="{% url 'users:list' %}">{% trans "user list" %}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-capitalize me-2"
                               href="{% url 'movie:manage-list' %}">{% trans 'movie list' %}</a>
                        </li>
                    {% endif %}
                    <li class="nav-item">
                        <form method="post" action="{% url 'users:logout' %}">
                            {% csrf_token %}
                            <button class="nav-link text-capitalize me-2 bg-transparent border-0"
                                    type="submit">
                                {% trans 'logout' %}
                            </button>
                        </form>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>